name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: install firebase functions
        run: sudo npm install firebase-functions@latest
      - name: install firebase admin
        run: sudo firebase-admin@latest --save
      - name: install firebase tools
        run: sudo npm install -g firebase-tools
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        run: firebase deploy --token 1//0gR8MXeh2RH6BCgYIARAAGBASNwF-L9Ir70uE2vB6vqq3xWnL-NnMaIOP-lQhdXiGH5I0jICgyRTVihoDcxVnjVI2AxXXifo-mgM
