name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present        
      - name: install firestore
        run: sudo npm install -g firebase-tools
      - name: install firebase functions
        run: sudo npm install firebase-functions@latest
      - name: install firebase admin
        run: sudo npm install firebase-admin@latest --save
      - name: install firebase tools
        run: sudo npm install -g firebase-tools

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: 1//0gR8MXeh2RH6BCgYIARAAGBASNwF-L9Ir70uE2vB6vqq3xWnL-NnMaIOP-lQhdXiGH5I0jICgyRTVihoDcxVnjVI2AxXXifo-mgM
