name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: install firestore
          uses: npm install -g firebase-tools
      # - name: Checkout Repo
      #   uses: actions/checkout@master
      # - name: install firebase
      #   run: npm install firebase-functions@latest firebase-admin@latest --save
      # - name: install firebase-tools
      #   run: npm install firebase-tools
      # - name: change directory
      #   run: cd functions
      # - name: Install Dependencies
      #   run: npm install
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        uses: firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: 1//0gR8MXeh2RH6BCgYIARAAGBASNwF-L9Ir70uE2vB6vqq3xWnL-NnMaIOP-lQhdXiGH5I0jICgyRTVihoDcxVnjVI2AxXXifo-mgM
